### ISSUE TITLE
ESP32 "BRICKED" 

### ISSUE THREAD

**Issue by wilhelmzeuschner** [G6EJD/ESP32-42e-Paper-Weather-Display-#2]
After uploading the ESP32_OWM_Current_Forecast_Streaming_75on42_epaper_v1 to my ESP32 it did initially work fine but I noticed an enormous battery drain.
I'm not sure whether this version of the program uses the NVS but this seemed to be the problem. I have never used this particular ESP32 with any other programs other that from here: https://github.com/G6EJD/ESP32-e-Paper-Weather-Display
Therefore it could be an issue within the "ESP32-e-Paper-Weather-Display" sketches.

Solution: https://esp32.com/viewtopic.php?t=2809

I could fix the issue but it's a mystery to me why this happened... 😕 

![bricked](https://user-images.githubusercontent.com/37621765/41818161-147d6774-77a9-11e8-8695-fa740abadb96.PNG)
![erase](https://user-images.githubusercontent.com/37621765/41818165-1f0b3338-77a9-11e8-884b-6d7f7d265abf.PNG)

Note: I am sure that I'm using the correct settings for flashing my particular model.

**Comment by G6EJD** [comment]
There is nothing in my code that uses NVS Flash, this is most likely to have occurred due to previous or current use of the ESP32. Every line in your stack trace refers to internal libraries that are nothing to do with the e-paper code. Try downloading the code again and I see you have reset your device now.
Is your location listed in the OWM list of weather stations?

**Comment by wilhelmzeuschner** [comment]
Since it works now, I have closed the Issue. My best guess is that something must have written to the NVS in  a way that corrupted something, maybe the file-system... If I remember correctly, some versions of the Weather Station Sketch used the Preferences library which uses the NVS if I'm not mistaken.

**Comment by G6EJD** [comment]
Thanks. Maybe the libraries write to NVS but I’m only using the screen driver and so they should not there is a lot of cross-referencing between libraries which is quite hard to track.
